<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <Title>Lombiq Chart.js for Orchard Core - Samples</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2021, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Chart.js for Orchard Core - Samples: Sample content that demonstrates the features of Lombiq Chart.js module for Orchard Core.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Chart.js</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Chart.js</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Chart.js/blob/dev/Lombiq.ChartJs.Samples/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentFields" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18937" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.ChartJs\Lombiq.ChartJs.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(NuGetBuild)' == 'true'">
    <!-- This is needed because we must use the same in Lombiq.ChartJs.Tests.UI.csproj. Embedded and portalbe DebugTypes
    can't be mixed within the repository because we should set "dotnet-pack-include-symbols: false" to avoid "The
    package does not contain any symbol (.pdb) files." during NuGet publishing. -->
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <NpmDotnetPrebuildWatchedFiles Remove="Assets\Styles\chartjs-samples.scss" />
  </ItemGroup>

</Project>
