<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.6.osoe-1208" />

  <PropertyGroup>
    <Title>Lombiq Chart.js for Orchard Core</Title>
    <CopyrightYear>2021</CopyrightYear>
    <DescriptionBody>An Orchard Core wrapper around the Chart.js library for displaying datasets as various charts. See the project website for detailed documentation.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Chart.js;chart</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Chart.js</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(NuGetBuild)' == 'true'">
    <!-- This is needed because we must use the same in Lombiq.ChartJs.Tests.UI.csproj. Embedded and portalbe DebugTypes
    can't be mixed within the repository because we should set "dotnet-pack-include-symbols: false" to avoid "The
    package does not contain any symbol (.pdb) files." during NuGet publishing. -->
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.6.osoe-1208" />
</Project>
