<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Chart.js for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2021, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Chart.js for Orchard Core: An Orchard Core wrapper around the Chart.js library for displaying datasets as various charts. See the project website for detailed documentation.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Chart.js;chart</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Chart.js</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Chart.js</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
    <None Include="..\Readme.md" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.71" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18896" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.MSBuild.LibMan.Targets" Version="1.0.0-alpha.12.nest-643" />
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.0.osoe-925" />
    <PackageReference Include="Lombiq.HelpfulLibraries.Attributes" Version="12.6.1-alpha.0.osoe-925" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    <PackageReference Include="Lombiq.HelpfulLibraries.SourceGenerators" Version="12.6.1-alpha.0.osoe-925" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <PropertyGroup Condition="'$(NuGetBuild)' == 'true'">
    <!-- This is needed because we must use the same in Lombiq.ChartJs.Tests.UI.csproj. Embedded and portalbe DebugTypes
    can't be mixed within the repository because we should set "dotnet-pack-include-symbols: false" to avoid "The
    package does not contain any symbol (.pdb) files." during NuGet publishing. -->
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true'"/>

</Project>
