name: Publish to NuGet

on:
  push:
    tags:
      - v*

jobs:
  publish-nuget:
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@issue/OSOE-751
    secrets:
      API_KEY: ${{ secrets.DEFAULT_NUGET_PUBLISH_API_KEY }}
    with:
      # Needed because the DebugType is set to "embedded" in the project files which results in empty snupkg files. To
      # avoid the "The package does not contain any symbol (.pdb) files." error during NuGet publishing we should set
      # this to "false".
      dotnet-pack-include-symbols: "false"
