name: Publish to NuGet

on:
  push:
    tags:
      - v*

jobs:
  publish-nuget:
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@dev
    secrets:
      API_KEY: ${{ secrets.DEFAULT_NUGET_PUBLISH_API_KEY }}
    with:
      # This is because the DebugType is set to "embedded" in the project files which results empty snupkg files. To avoid
      # "The package does not contain any symbol (.pdb) files." nuget push error we should set this to "false".
      dotnet-pack-include-symbols: "false"
